main: eu.hiddenite.fun.FunPlugin
name: HiddeniteFun
version: 1.0.0
api-version: 1.16
author: Hiddenite
commands:
  hat:
    permission: hiddenite.hat
    description: "Switch your helmet to an absurd one!"
    usage: "/<command>"
  iframe:
    permission: hiddenite.iframe
    description: "Make item frames invisible!"
    usage: "/<command>"
  sit:
    permission: hiddenite.sit
    description: "Sit anywhere when you are tired."
    usage: "/<command>"
  give-head:
    permission: hiddenite.give-head
    description: "Create fake kill heads."
    usage: "/<command> <killer> <victim>"
permissions:
  hiddenite.hat:
    description: "Allows the /hat command"
    default: op
  hiddenite.iframe:
    description: "Allows the /iframe command"
    default: op
  hiddenite.sit:
    description: "Allows the /sit command"
    default: op
  hiddenite.give-head:
    description: "Allows the /give-head command"
    default: op
  hiddenite.fun.spore_blossom:
    description: "Allows the player to craft spore blossom."
    default: op
